### ISSUE TITLE
在哪可以下载到论文呢

### ISSUE THREAD

**Issue by maozhiqiang** [silyfox/iscslp-98-demo#1]
听了一下demo 效果挺棒的，在哪可以下载到论文呢

**Comment by silyfox** [comment]
论文在投中，暂时还不能下载。




------------------ 原始邮件 ------------------
发件人: z.q.mao <notifications@github.com&gt;
发送时间: 2020年9月15日 17:31
收件人: silyfox/iscslp-98-demo <iscslp-98-demo@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[silyfox/iscslp-98-demo] 在哪可以下载到论文呢 (#1)

**Comment by silyfox** [comment]
你是在哪看见这个链接地址了呀？




------------------ 原始邮件 ------------------
发件人: z.q.mao <notifications@github.com&gt;
发送时间: 2020年9月15日 17:31
收件人: silyfox/iscslp-98-demo <iscslp-98-demo@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[silyfox/iscslp-98-demo] 在哪可以下载到论文呢 (#1)

**Comment by maozhiqiang** [comment]
在git中看到的，觉得挺有意思的，想看看原文
